### ISSUE TITLE
Wrong github link on thememaker.site

### ISSUE THREAD

**Issue by MasterGroosha** [danielpetrica/Telegram-Desktop-themes-maker#2]
On thememaker.site, the github link is `https://github.com/danielpetrica/Telegram-Desktop-themes-makers`, however the last letter "s" is redundant.

**Comment by danielpetrica** [comment]
That's a ctrl-s without ctrl! :)

**Comment by danielpetrica** [comment]
I changed it already

**Comment by MasterGroosha** [comment]
Thanks
